version: '3.1'

services:
  # main-service:
  #   image: zemanqwerty/itssl:main-service
  #   ports:
  #     - 5010:5010
  #   volumes:
  #     - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/path/in/container/fullchain.pem
  #     - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/path/in/container/privkey.pem
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: root
  #     DB_PASSWORD: itsslmaindb
  #     DB_NAME: itssl-db
  #     JWT_ACCESS_SECRET_KEY: secretaccesskeyforitssl
  #     JWT_REFRESH_SECRET_KEY: secretrefreshkeyforitssl
  #     BASE_ADMIN_EMAIL: admin@gmail.com
  #     BASE_ADMIN_PASSWORD: qgDcsQhsLa
  #   restart: unless-stopped

  db:
    image:  postgres:11
    ports:
      - 32700:5432
    volumes:
      - data:/var/lib/postgresql/data
    command: postgres -c stats_temp_directory=/tmp
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: itsslmaindb
      POSTGRES_DB: itssl-db
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: zeman@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123456

volumes:
  data: